// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package system

import (
	"app/internal/provider"
	"context"
)

// Injectors from wire.go:

func New(ctx context.Context) (*App, error) {
	example, err := provider.ProvideExample(ctx)
	if err != nil {
		return nil, err
	}
	fiberFeatureSet := provider.FiberFeatureSet{
		Example: example,
	}
	fiber, err := provider.MakeFiber(fiberFeatureSet)
	if err != nil {
		return nil, err
	}
	gorm, err := provider.ProvideGORM(ctx)
	if err != nil {
		return nil, err
	}
	watermill, err := provider.ProvideWatermill(ctx)
	if err != nil {
		return nil, err
	}
	work, err := provider.ProvideWork()
	if err != nil {
		return nil, err
	}
	app := &App{
		Fiber:     fiber,
		GORM:      gorm,
		Watermill: watermill,
		Work:      work,
	}
	return app, nil
}
