// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package system

import (
	"app/internal/provider"
	"context"
)

// Injectors from wire.go:

func New(ctx context.Context) (*App, error) {
	otel, err := provider.ProvideOtel()
	if err != nil {
		return nil, err
	}
	example, err := provider.ProvideExample(ctx, otel)
	if err != nil {
		return nil, err
	}
	fiberFeatureSet := provider.FiberFeatureSet{
		Example: example,
	}
	slog := provider.ProvideSlog()
	fiber, err := provider.MakeFiber(fiberFeatureSet, otel, slog)
	if err != nil {
		return nil, err
	}
	gorm, err := provider.ProvideGorm(ctx)
	if err != nil {
		return nil, err
	}
	watermill, err := provider.ProvideWatermill(ctx, slog)
	if err != nil {
		return nil, err
	}
	work, err := provider.ProvideWork()
	if err != nil {
		return nil, err
	}
	email, err := provider.ProvideEmail()
	if err != nil {
		return nil, err
	}
	app := &App{
		Otel:      otel,
		Fiber:     fiber,
		Gorm:      gorm,
		Watermill: watermill,
		Work:      work,
		Slog:      slog,
		Email:     email,
	}
	return app, nil
}
