services:
  web:
    image: node:24-alpine
    volumes:
      - ./web:/app
    working_dir: /app
    ports:
      - "5173:5173"
    depends_on:
      - app
    command: npm run dev -- --host
    environment:
      ENV: docker
