// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package example

import (
	"context"
)

// Injectors from wire.go:

func New(ctx context.Context, cfg Config) (*Example, error) {
	example := &Example{}
	return example, nil
}
