// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"app/pkg/auth"
)

// Injectors from wire.go:

func New() (*App, error) {
	db := NewGormDB()
	userRepo := auth.NewUserRepo(db)
	handler := auth.NewHandler(userRepo)
	app := NewApp(db, handler)
	return app, nil
}
