// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"app/pkg/user/internal/action"
	"app/pkg/user/internal/content"
	"app/pkg/user/internal/resource"
	"context"
)

// Injectors from wire.go:

func New(ctx context.Context, cfg Config) (*User, error) {
	tracer := cfg.Tracer
	changePassword := &action.ChangePassword{
		Tracer: tracer,
	}
	forgotPassword := &action.ForgotPassword{}
	resetPassword := &action.ResetPassword{}
	signInByEmail := &action.SignInByEmail{}
	signOut := &action.SignOut{}
	db := cfg.DB
	mailer := cfg.Mailer
	signUpByEmail := &action.SignUpByEmail{
		Tracer: tracer,
		DB:     db,
		Mailer: mailer,
	}
	verifySignUpByEmail := &action.VerifySignUpByEmail{}
	currentSession := &content.CurrentSession{}
	list := &resource.List{
		Tracer: tracer,
		DB:     db,
	}
	one := &resource.One{}
	user := &User{
		actionChangePassword:      changePassword,
		actionForgotPassword:      forgotPassword,
		actionResetPassword:       resetPassword,
		actionSignInByEmail:       signInByEmail,
		actionSignOut:             signOut,
		actionSignUpByEmail:       signUpByEmail,
		actionVerifySignUpByEmail: verifySignUpByEmail,
		contentCurrentSession:     currentSession,
		resourceList:              list,
		resourceOne:               one,
	}
	return user, nil
}
